import { InfoLandingPage } from './svg/InfoLandingPage'
export { Logo } from './svg/Logo'
export { LogoLetra } from './svg/LogoLetra'
export { FogueteFumaca } from './svg/FogueteFumaca'
export { IconYoutube } from './svg/IconYoutube'
export { IconLinkedin } from './svg/IconLinkedin'
export { IconInstagram } from './svg/IconInstagram'
export { IconFlag } from './svg/IconFlag'
export { IconMedal } from './svg/IconMedal'
export { IconStar } from './svg/IconStar'
export { IconSupport } from './svg/IconSupport'
export { IconCoin } from './svg/IconCoin'
export { IconCheck } from './svg/IconCheck'
export { IconApi } from './svg/IconApi'
export { IconPeople } from './svg/IconPeople'
export { IconDoubleCheck } from './svg/IconDoubleCheck'
export { IconChart } from './svg/IconChart'
export { IconTemplate } from './svg/IconTemplate'
export { IconBlocklist } from './svg/IconBlocklist'
export { IconCloud } from './svg/IconCloud'
export { IconClock } from './svg/IconClock'
export { IconShield } from './svg/IconShield'
export { IconEyou } from './svg/IconEyou'
export { IconEyouFull } from './svg/IconEyouFull'
export { IconPhone } from './svg/IconPhone'
export { IconEmail } from './svg/IconEmail'
export { PersonForm } from './svg/PersonForm'
export { IconProductSms } from './svg/IconProductSms'
export { IconProductTelephony } from './svg/IconProductTelephony'
export { IconProductWhatsapp } from './svg/IconProductWhatsapp'
export { PersonAbout } from './svg/PersonAbout'

//ICONS SERVICOS
export { IconServicosSMSBanner } from './svg/IconServicosSMSBanner'
export { IconServicosTitulo } from './svg/IconServicosTitulo'
export { IconServicosMedalha } from './svg/IconServicosMedalha'
export { IconServicosConversa } from './svg/IconServicosConversa'
export { IconServicosFolhaComRelogio } from './svg/IconServicosFolhaComRelogio'
export { IconServicosGlobo } from './svg/IconServicosGlobo'
export { IconServicosBalaoLapis } from './svg/IconServicosBalaoLapis'
export { IconServicosIosAndroid } from './svg/IconServicosIosAndroid'
export { IconServicosAltaReceptividade } from './svg/IconServicosAltaReceptividade'
export { IconServicosAppsBanner } from './svg/IconServicosAppsBanner'
export { IconServicosChaton } from './svg/IconServicosChaton'
export { IconServicosChatbot } from './svg/IconServicosChatbot'
export { IconServicosPush } from './svg/IconServicosPush'
export { IconServicosEmail } from './svg/IconServicosEmail'
export { IconServicosEnriquece } from './svg/IconServicosEnriquece'
export { IconServicosBoleto } from './svg/IconServicosBoleto'
export { IconServicosLinkCurto } from './svg/IconServicosLinkCurto'
export { IconServicosWpBanner } from './svg/IconServicosWpBanner'
export { IconServicosMapa } from './svg/IconServicosMapa'
export { IconServicosCelularRelogio } from './svg/IconServicosCelularRelogio'
export { IconServicosWhatsapp } from './svg/IconServicosWhatsapp'
export { IconServicosWhatsappMassa } from './svg/IconServicosWhatsappMassa'
export { IconServicosWhatsappConsulta } from './svg/IconServicosWhatsappConsulta'
export { IconServicosChatbotBanner } from './svg/IconServicosChatbotBanner'
export { IconServicosSuporte } from './svg/IconServicosSuporte'
export { IconServicosMoedas } from './svg/IconServicosMoedas'
export { IconServicosCheck } from './svg/IconServicosCheck'
export { IconServicosIntegracao } from './svg/IconServicosIntegracao'
export { IconServicosEquipe } from './svg/IconServicosEquipe'
export { IconServicosDoubleCheck } from './svg/IconServicosDoubleCheck'
export { IconServicosBars } from './svg/IconServicosBars'
export { IconServicosCustomizacao } from './svg/IconServicosCustomizacao'
export { IconServicosBlacklist } from './svg/IconServicosBlacklist'
export { IconServicosOperadoras } from './svg/IconServicosOperadoras'
export { IconServicosTimer } from './svg/IconServicosTimer'
export { IconServicosEscudo } from './svg/IconServicosEscudo'
export { IconServicosCheckTrue } from './svg/IconServicosCheckTrue'
//END  ICONS SERVICOS

export { QSBalao1 } from './svg/QSBalao1'
export { QSBalao2 } from './svg/QSBalao2'
export { QSBalao3 } from './svg/QSBalao3'
export { QSBalao4 } from './svg/QSBalao4'
export { QSBalao5 } from './svg/QSBalao5'
export { QSBalaoVerde } from './svg/QSBalaoVerde'
export { QSBalaoConversa } from './svg/QSBalaoConversa'
export { QSIconDataCenter } from './svg/QSIconDataCenter'
export { IconMultisessao } from './svg/IconMultisessao'
export { IconChamadoTecnico } from './svg/IconChamadoTecnico'
export { IconTecnologia } from './svg/IconTecnologia'
export { IconSemSurpresa } from './svg/IconSemSurpresa'

export {BgContatoRight} from './svg/BgContatoRight'
export {IconProductApps} from './svg/IconProductApps'
export {IconServicosHotPage} from './svg/IconServicosHotPage'
export {IconServicosHigienizacao} from './svg/IconServicosHigienizacao'
export {IconServicosPortabilidade} from './svg/IconServicosPortabilidade'
export {IconServicosVoip} from './svg/IconServicosVoip'
export {IconServicosMensagemVoz} from './svg/IconServicosMensagemVoz'
export {IconTituloSolucoes} from './svg/IconTituloSolucoes'
export {IconServicosBalaoMensagem} from './svg/IconServicosBalaoMensagem'
